-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg42FiORdWJ7r/7PqT
SgiXINFesYhc+HXXkBT1CB+SHD+gCgYIKoZIzj0DAQehRANCAASAMJQw8hdKyXQU
GVesZzaprr/Y2SC+NFapunpwSFf3ggzfMGmx4CTZeDxCjovHZJq20fyrjyME8RL+
vjWdK7pW
-----END PRIVATE KEY-----